require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/marvel_stories", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MarvelStory. As you add validations to MarvelStory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MarvelStory.create! valid_attributes
      get marvel_stories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      marvel_story = MarvelStory.create! valid_attributes
      get marvel_story_url(marvel_story)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_marvel_story_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      marvel_story = MarvelStory.create! valid_attributes
      get edit_marvel_story_url(marvel_story)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MarvelStory" do
        expect {
          post marvel_stories_url, params: { marvel_story: valid_attributes }
        }.to change(MarvelStory, :count).by(1)
      end

      it "redirects to the created marvel_story" do
        post marvel_stories_url, params: { marvel_story: valid_attributes }
        expect(response).to redirect_to(marvel_story_url(MarvelStory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MarvelStory" do
        expect {
          post marvel_stories_url, params: { marvel_story: invalid_attributes }
        }.to change(MarvelStory, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post marvel_stories_url, params: { marvel_story: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested marvel_story" do
        marvel_story = MarvelStory.create! valid_attributes
        patch marvel_story_url(marvel_story), params: { marvel_story: new_attributes }
        marvel_story.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the marvel_story" do
        marvel_story = MarvelStory.create! valid_attributes
        patch marvel_story_url(marvel_story), params: { marvel_story: new_attributes }
        marvel_story.reload
        expect(response).to redirect_to(marvel_story_url(marvel_story))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        marvel_story = MarvelStory.create! valid_attributes
        patch marvel_story_url(marvel_story), params: { marvel_story: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested marvel_story" do
      marvel_story = MarvelStory.create! valid_attributes
      expect {
        delete marvel_story_url(marvel_story)
      }.to change(MarvelStory, :count).by(-1)
    end

    it "redirects to the marvel_stories list" do
      marvel_story = MarvelStory.create! valid_attributes
      delete marvel_story_url(marvel_story)
      expect(response).to redirect_to(marvel_stories_url)
    end
  end
end
